language: c
sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
    - cmake
    - libbsd-dev
    - check

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && bin/check_bsh
